[update_manager klipper-adxl-auto]
type: git_repo
path: ~/klipper-adxl-auto
origin: https://github.com/joseto1298/klipper-adxl-auto.git
managed_services: klipper moonraker
primary_branch: main
install_script: setup.sh
